### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by psnszsn** [flathub/io.github.gillesdegottex.FMIT#11]
Please add `--socket=wayland` to the manifest file so FMIT can run on wayland.
`flatpak run --socket=wayland io.github.gillesdegottex.FMIT` works, but it would be nice not to have to use this workaround.

**Comment by dsboger** [comment]
I've pushed the fix in a branch, but FMIT requires some other fixes in other to build properly on flathub. Once that is sorted out, I'll merge the branch. Thanks for reporting!

Out of curiosity: did you confirm it is not running on XWayland? Does it fail without `--socket=wayland`?

**Comment by psnszsn** [comment]
QT defaults to Wayland in Wayland sessions, but uses XWayland as a fallback.

Running without `--socket=wayland` fails on my system because i have set `QT_QPA_PLATFORM` to `wayland-egl`. To use XWayland i have to run `flatpak run --env=QT_QPA_PLATFORM=xcb io.github.gillesdegottex.FMIT`.

**Comment by hfiguiere** [comment]
Sometime you have to use `--env=QT_QPA_PLATFORM=xcb`. Also it needs `dri`.

Anyway PR #12 include this too.

**Comment by hfiguiere** [comment]
This has been in for a while.
