### ISSUE TITLE
JACK does not work anymore

### ISSUE THREAD

**Issue by dsboger** [flathub/io.github.gillesdegottex.FMIT#8]
Since commit https://github.com/flatpak/flatpak/commit/89e2b6679cd4a59c15b225c0c6c0e1293ae83f7d it is no longer possible for a JACK client inside Flatpak sandbox to communicate with a JACK server in the host.

**Comment by gillesdegottex** [comment]
Thanks for opening this issue.
Concerning flatpak:
Is it an independant package management, right?
I see that we're still building the deb file anyway for each release.

**Comment by BrunoVernay** [comment]
Disabling Jack for the Flatpak package  (indeed, nothing changes for other packages: Deb, Rpm ...) seems the reasonable answer. 
According to the PipeWire Wiki, Jack support can be tested in the "work branch" https://github.com/PipeWire/pipewire/wiki/JACK .  Definitively not available in the distro repositories, not even latest Fedora rawhide.   Better wait and see, before releasing a FlatPack for the masses ...

**Comment by dsboger** [comment]
@gillesdegottex yes, Flatpak is an alternative packaging/installation system that does not affect debs. This issue is caused by Flatpak sandboxing that prevents FMIT from seeing JACK socket and shared memory files. There used to be a way to punch a special hole in the sandbox, but that is no longer allowed by Flatpak.

**Comment by gillesdegottex** [comment]
Well, so I guess, we don't have any choice then removing Jack from flatpack, right ?

BTW, All of flatpack packages are thus now incompatible with Jack ?

**Comment by hfiguiere** [comment]
Reopening this. Since Freedesktop 20.08 with can use Jack using pipewire-jack.
